---
- name: remove Apache web server
  package: name=apache2 state=absent

- name: install nginx web server
  package: name=nginx state=present

- name: start and enable nginx service
  service: name=nginx state=started enabled=yes

- name: remove default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: generate a new configuration for Drupal
  template:
    src: drupal.conf
    dest: /etc/nginx/sites-available/drupal.conf
    owner: root
    group: root

- name: Create symbolic link to sites enabled
  shell: sudo ln -s /etc/nginx/sites-available/drupal.conf /etc/nginx/sites-enabled/
  args:
    chdir: "/"
  notify:
    - restart nginx

- meta: flush_handlers