---
- name: Remove Apache web server
  package: name=apache2 state=absent

- name: Install NGINX web server
  package: name=nginx state=present

- name: Start and enable nginx service
  service: name=nginx state=started enabled=yes

- name: Remove default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Generate a new configuration for Drupal
  template:
    src: drupal.conf
    dest: /etc/nginx/sites-available/drupal.conf
    owner: root
    group: root
  vars:
    root: "{{ drupal_site_path }}/drupal/web"

- name: Create symbolic link to sites enabled
  shell: sudo ln -s /etc/nginx/sites-available/drupal.conf /etc/nginx/sites-enabled/
  args:
    chdir: "/"
  notify:
    - restart nginx

- meta: flush_handlers