---
- name: Install CW Agent
  shell: dpkg -i -E ./amazon-cloudwatch-agent.deb
  become: true
  args:
    chdir: "/"

- name: Fetch the config and start the agent
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
  become: true
  args:
    chdir: "/"